/** @type {import('tailwindcss').Config} */
// Theme mirrors lib/theme/tokens.ts — keep both in sync (see CONTRACT.md §Theme).
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}', './lib/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#596244',
        'on-primary': '#ffffff',
        'primary-container': '#8e9775',
        'on-primary-container': '#272f15',
        'primary-fixed': '#dee7c0',
        'primary-fixed-dim': '#c1cba6',
        'on-primary-fixed': '#171e06',
        'on-primary-fixed-variant': '#424a2e',
        'inverse-primary': '#c1cba6',
        'surface-tint': '#596244',
        secondary: '#7d562d',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffca98',
        'on-secondary-container': '#7a532a',
        'secondary-fixed': '#ffdcbd',
        'secondary-fixed-dim': '#f0bd8b',
        'on-secondary-fixed': '#2c1600',
        'on-secondary-fixed-variant': '#623f18',
        tertiary: '#765a05',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b08f3b',
        'on-tertiary-container': '#392a00',
        'tertiary-fixed': '#ffdf96',
        'tertiary-fixed-dim': '#e7c268',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#5a4400',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
        surface: '#fcf9f8',
        'on-surface': '#1b1c1c',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'surface-variant': '#e4e2e1',
        'on-surface-variant': '#46483f',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        outline: '#77786e',
        'outline-variant': '#c7c7bb',
      },
      fontFamily: {
        'h-regular': ['HankenGrotesk_400Regular'],
        'h-medium': ['HankenGrotesk_500Medium'],
        'h-semibold': ['HankenGrotesk_600SemiBold'],
        'h-bold': ['HankenGrotesk_700Bold'],
        'b-regular': ['Inter_400Regular'],
        'b-medium': ['Inter_500Medium'],
        'b-semibold': ['Inter_600SemiBold'],
        'b-bold': ['Inter_700Bold'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.96px' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.32px' }],
        'headline-lg': ['32px', { lineHeight: '40px' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.14px' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.48px' }],
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'section-gap': '64px',
        'container-padding-mobile': '20px',
        'container-padding-desktop': '80px',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
